spring.application.name=reservation-management
server.port=8083

# mysql database connection properties
#spring.datasource.url=jdbc:mysql://localhost:3306/reservation_management
#spring.datasource.username=root
#spring.datasource.password=Rittik@95174
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:h2:file:~/data/reservation_types;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# travel planner service URLs
travel.planner.service.base_url = http://localhost:8082/
travel.planner.service.url = api/
travel.planner.service.skip = false
